name: upload
on: [push]
jobs:
  release:
    name: Release pushed tag3
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          if ! gh release view $tag; then
            echo "aaaaaaaaaaa"
            gh release create "$tag" \
                --repo="$GITHUB_REPOSITORY" \
                --title="${tag#v}"
          fi
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run rpmbuild on RPM spec to produce package
        id: rpm
        uses: naveenrajm7/rpmbuild@master
        with:
          spec_file: build/package/rpm/healthd.spec
