name: upload
on: [push]
jobs:
  release:
    name: Release pushed tag3
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          if ! gh release view test; then
            echo "aaaaaaaaaaa"
            #gh release create test \
            #    --repo="$GITHUB_REPOSITORY" \
            #    --title="${tag#v}"
          fi
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: test
        run: |
          sudo echo "aaa" > /root/aaaa
      - name: bbbb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          sudo rpmbuild -ba build/package/rpm/healthd.spec

